//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class HystoryStatu
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int IdLicence { get; set; }
        public int IdStatusLicence { get; set; }
    
        public virtual Licence Licence { get; set; }
        public virtual StatusLicence StatusLicence { get; set; }
    }
}
