//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licence
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Licence()
        {
            this.HystoryStatus = new HashSet<HystoryStatu>();
        }
    
        public int Id { get; set; }
        public string LicenceDate { get; set; }
        public string ExpireDate { get; set; }
        public string Categories { get; set; }
        public int LicenceSeries { get; set; }
        public int LicenceNumber { get; set; }
        public int IdDriver { get; set; }
        public int IdStatus { get; set; }
    
        public virtual Driver Driver { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HystoryStatu> HystoryStatus { get; set; }
        public virtual StatusLicence StatusLicence { get; set; }
    }
}
