//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductionPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionCode
    {
        public int Id { get; set; }
        public string NameEng { get; set; }
        public string NameRu { get; set; }
        public Nullable<int> SubjectCode { get; set; }
        public string Code { get; set; }
        public Nullable<int> OkatoCode { get; set; }
        public string Gost { get; set; }
    }
}
